/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SearchRouteImport } from './routes/search'
import { Route as RunsRouteImport } from './routes/runs'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HistoryIdRouteImport } from './routes/history.$id'
import { Route as ApiPublicLeadsStatusRouteImport } from './routes/api/public/leads.status'
import { Route as ApiPublicLeadsStartRouteImport } from './routes/api/public/leads.start'
import { Route as ApiPublicApifyRunsRouteImport } from './routes/api/public/apify.runs'
import { Route as ApiPublicApifyImportRouteImport } from './routes/api/public/apify.import'

const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const RunsRoute = RunsRouteImport.update({
  id: '/runs',
  path: '/runs',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryIdRoute = HistoryIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => HistoryRoute,
} as any)
const ApiPublicLeadsStatusRoute = ApiPublicLeadsStatusRouteImport.update({
  id: '/api/public/leads/status',
  path: '/api/public/leads/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicLeadsStartRoute = ApiPublicLeadsStartRouteImport.update({
  id: '/api/public/leads/start',
  path: '/api/public/leads/start',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicApifyRunsRoute = ApiPublicApifyRunsRouteImport.update({
  id: '/api/public/apify/runs',
  path: '/api/public/apify/runs',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicApifyImportRoute = ApiPublicApifyImportRouteImport.update({
  id: '/api/public/apify/import',
  path: '/api/public/apify/import',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/history': typeof HistoryRouteWithChildren
  '/runs': typeof RunsRoute
  '/search': typeof SearchRoute
  '/history/$id': typeof HistoryIdRoute
  '/api/public/apify/import': typeof ApiPublicApifyImportRoute
  '/api/public/apify/runs': typeof ApiPublicApifyRunsRoute
  '/api/public/leads/start': typeof ApiPublicLeadsStartRoute
  '/api/public/leads/status': typeof ApiPublicLeadsStatusRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/history': typeof HistoryRouteWithChildren
  '/runs': typeof RunsRoute
  '/search': typeof SearchRoute
  '/history/$id': typeof HistoryIdRoute
  '/api/public/apify/import': typeof ApiPublicApifyImportRoute
  '/api/public/apify/runs': typeof ApiPublicApifyRunsRoute
  '/api/public/leads/start': typeof ApiPublicLeadsStartRoute
  '/api/public/leads/status': typeof ApiPublicLeadsStatusRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/history': typeof HistoryRouteWithChildren
  '/runs': typeof RunsRoute
  '/search': typeof SearchRoute
  '/history/$id': typeof HistoryIdRoute
  '/api/public/apify/import': typeof ApiPublicApifyImportRoute
  '/api/public/apify/runs': typeof ApiPublicApifyRunsRoute
  '/api/public/leads/start': typeof ApiPublicLeadsStartRoute
  '/api/public/leads/status': typeof ApiPublicLeadsStatusRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/history'
    | '/runs'
    | '/search'
    | '/history/$id'
    | '/api/public/apify/import'
    | '/api/public/apify/runs'
    | '/api/public/leads/start'
    | '/api/public/leads/status'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/history'
    | '/runs'
    | '/search'
    | '/history/$id'
    | '/api/public/apify/import'
    | '/api/public/apify/runs'
    | '/api/public/leads/start'
    | '/api/public/leads/status'
  id:
    | '__root__'
    | '/'
    | '/history'
    | '/runs'
    | '/search'
    | '/history/$id'
    | '/api/public/apify/import'
    | '/api/public/apify/runs'
    | '/api/public/leads/start'
    | '/api/public/leads/status'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HistoryRoute: typeof HistoryRouteWithChildren
  RunsRoute: typeof RunsRoute
  SearchRoute: typeof SearchRoute
  ApiPublicApifyImportRoute: typeof ApiPublicApifyImportRoute
  ApiPublicApifyRunsRoute: typeof ApiPublicApifyRunsRoute
  ApiPublicLeadsStartRoute: typeof ApiPublicLeadsStartRoute
  ApiPublicLeadsStatusRoute: typeof ApiPublicLeadsStatusRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/runs': {
      id: '/runs'
      path: '/runs'
      fullPath: '/runs'
      preLoaderRoute: typeof RunsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history/$id': {
      id: '/history/$id'
      path: '/$id'
      fullPath: '/history/$id'
      preLoaderRoute: typeof HistoryIdRouteImport
      parentRoute: typeof HistoryRoute
    }
    '/api/public/leads/status': {
      id: '/api/public/leads/status'
      path: '/api/public/leads/status'
      fullPath: '/api/public/leads/status'
      preLoaderRoute: typeof ApiPublicLeadsStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/leads/start': {
      id: '/api/public/leads/start'
      path: '/api/public/leads/start'
      fullPath: '/api/public/leads/start'
      preLoaderRoute: typeof ApiPublicLeadsStartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/apify/runs': {
      id: '/api/public/apify/runs'
      path: '/api/public/apify/runs'
      fullPath: '/api/public/apify/runs'
      preLoaderRoute: typeof ApiPublicApifyRunsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/apify/import': {
      id: '/api/public/apify/import'
      path: '/api/public/apify/import'
      fullPath: '/api/public/apify/import'
      preLoaderRoute: typeof ApiPublicApifyImportRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface HistoryRouteChildren {
  HistoryIdRoute: typeof HistoryIdRoute
}

const HistoryRouteChildren: HistoryRouteChildren = {
  HistoryIdRoute: HistoryIdRoute,
}

const HistoryRouteWithChildren =
  HistoryRoute._addFileChildren(HistoryRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HistoryRoute: HistoryRouteWithChildren,
  RunsRoute: RunsRoute,
  SearchRoute: SearchRoute,
  ApiPublicApifyImportRoute: ApiPublicApifyImportRoute,
  ApiPublicApifyRunsRoute: ApiPublicApifyRunsRoute,
  ApiPublicLeadsStartRoute: ApiPublicLeadsStartRoute,
  ApiPublicLeadsStatusRoute: ApiPublicLeadsStatusRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
