/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ApiPublicLeadsStatusRouteImport } from './routes/api/public/leads.status'
import { Route as ApiPublicLeadsStartRouteImport } from './routes/api/public/leads.start'

const ApiPublicLeadsStatusRoute = ApiPublicLeadsStatusRouteImport.update({
  id: '/api/public/leads/status',
  path: '/api/public/leads/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicLeadsStartRoute = ApiPublicLeadsStartRouteImport.update({
  id: '/api/public/leads/start',
  path: '/api/public/leads/start',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/api/public/leads/start': typeof ApiPublicLeadsStartRoute
  '/api/public/leads/status': typeof ApiPublicLeadsStatusRoute
}
export interface FileRoutesByTo {
  '/api/public/leads/start': typeof ApiPublicLeadsStartRoute
  '/api/public/leads/status': typeof ApiPublicLeadsStatusRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/api/public/leads/start': typeof ApiPublicLeadsStartRoute
  '/api/public/leads/status': typeof ApiPublicLeadsStatusRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/api/public/leads/start' | '/api/public/leads/status'
  fileRoutesByTo: FileRoutesByTo
  to: '/api/public/leads/start' | '/api/public/leads/status'
  id: '__root__' | '/api/public/leads/start' | '/api/public/leads/status'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ApiPublicLeadsStartRoute: typeof ApiPublicLeadsStartRoute
  ApiPublicLeadsStatusRoute: typeof ApiPublicLeadsStatusRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/api/public/leads/status': {
      id: '/api/public/leads/status'
      path: '/api/public/leads/status'
      fullPath: '/api/public/leads/status'
      preLoaderRoute: typeof ApiPublicLeadsStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/leads/start': {
      id: '/api/public/leads/start'
      path: '/api/public/leads/start'
      fullPath: '/api/public/leads/start'
      preLoaderRoute: typeof ApiPublicLeadsStartRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  ApiPublicLeadsStartRoute: ApiPublicLeadsStartRoute,
  ApiPublicLeadsStatusRoute: ApiPublicLeadsStatusRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
