/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SearchRouteImport } from './routes/search'
import { Route as RunsRouteImport } from './routes/runs'
import { Route as LeadsRouteImport } from './routes/leads'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HistoryIndexRouteImport } from './routes/history.index'
import { Route as HistoryIdRouteImport } from './routes/history.$id'
import { Route as ApiPublicWebsiteAnalyzeRouteImport } from './routes/api/public/website.analyze'
import { Route as ApiPublicLeadsStatusRouteImport } from './routes/api/public/leads.status'
import { Route as ApiPublicLeadsStartRouteImport } from './routes/api/public/leads.start'
import { Route as ApiPublicInstagramAnalyzeRouteImport } from './routes/api/public/instagram.analyze'
import { Route as ApiPublicBrandAnalyzeRouteImport } from './routes/api/public/brand.analyze'
import { Route as ApiPublicApifyRunsRouteImport } from './routes/api/public/apify.runs'
import { Route as ApiPublicApifyImportRouteImport } from './routes/api/public/apify.import'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const RunsRoute = RunsRouteImport.update({
  id: '/runs',
  path: '/runs',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadsRoute = LeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryIndexRoute = HistoryIndexRouteImport.update({
  id: '/history/',
  path: '/history/',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryIdRoute = HistoryIdRouteImport.update({
  id: '/history/$id',
  path: '/history/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWebsiteAnalyzeRoute = ApiPublicWebsiteAnalyzeRouteImport.update({
  id: '/api/public/website/analyze',
  path: '/api/public/website/analyze',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicLeadsStatusRoute = ApiPublicLeadsStatusRouteImport.update({
  id: '/api/public/leads/status',
  path: '/api/public/leads/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicLeadsStartRoute = ApiPublicLeadsStartRouteImport.update({
  id: '/api/public/leads/start',
  path: '/api/public/leads/start',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicInstagramAnalyzeRoute =
  ApiPublicInstagramAnalyzeRouteImport.update({
    id: '/api/public/instagram/analyze',
    path: '/api/public/instagram/analyze',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicBrandAnalyzeRoute = ApiPublicBrandAnalyzeRouteImport.update({
  id: '/api/public/brand/analyze',
  path: '/api/public/brand/analyze',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicApifyRunsRoute = ApiPublicApifyRunsRouteImport.update({
  id: '/api/public/apify/runs',
  path: '/api/public/apify/runs',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicApifyImportRoute = ApiPublicApifyImportRouteImport.update({
  id: '/api/public/apify/import',
  path: '/api/public/apify/import',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/leads': typeof LeadsRoute
  '/runs': typeof RunsRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/history/$id': typeof HistoryIdRoute
  '/history/': typeof HistoryIndexRoute
  '/api/public/apify/import': typeof ApiPublicApifyImportRoute
  '/api/public/apify/runs': typeof ApiPublicApifyRunsRoute
  '/api/public/brand/analyze': typeof ApiPublicBrandAnalyzeRoute
  '/api/public/instagram/analyze': typeof ApiPublicInstagramAnalyzeRoute
  '/api/public/leads/start': typeof ApiPublicLeadsStartRoute
  '/api/public/leads/status': typeof ApiPublicLeadsStatusRoute
  '/api/public/website/analyze': typeof ApiPublicWebsiteAnalyzeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/leads': typeof LeadsRoute
  '/runs': typeof RunsRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/history/$id': typeof HistoryIdRoute
  '/history': typeof HistoryIndexRoute
  '/api/public/apify/import': typeof ApiPublicApifyImportRoute
  '/api/public/apify/runs': typeof ApiPublicApifyRunsRoute
  '/api/public/brand/analyze': typeof ApiPublicBrandAnalyzeRoute
  '/api/public/instagram/analyze': typeof ApiPublicInstagramAnalyzeRoute
  '/api/public/leads/start': typeof ApiPublicLeadsStartRoute
  '/api/public/leads/status': typeof ApiPublicLeadsStatusRoute
  '/api/public/website/analyze': typeof ApiPublicWebsiteAnalyzeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/leads': typeof LeadsRoute
  '/runs': typeof RunsRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/history/$id': typeof HistoryIdRoute
  '/history/': typeof HistoryIndexRoute
  '/api/public/apify/import': typeof ApiPublicApifyImportRoute
  '/api/public/apify/runs': typeof ApiPublicApifyRunsRoute
  '/api/public/brand/analyze': typeof ApiPublicBrandAnalyzeRoute
  '/api/public/instagram/analyze': typeof ApiPublicInstagramAnalyzeRoute
  '/api/public/leads/start': typeof ApiPublicLeadsStartRoute
  '/api/public/leads/status': typeof ApiPublicLeadsStatusRoute
  '/api/public/website/analyze': typeof ApiPublicWebsiteAnalyzeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/leads'
    | '/runs'
    | '/search'
    | '/settings'
    | '/history/$id'
    | '/history/'
    | '/api/public/apify/import'
    | '/api/public/apify/runs'
    | '/api/public/brand/analyze'
    | '/api/public/instagram/analyze'
    | '/api/public/leads/start'
    | '/api/public/leads/status'
    | '/api/public/website/analyze'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/leads'
    | '/runs'
    | '/search'
    | '/settings'
    | '/history/$id'
    | '/history'
    | '/api/public/apify/import'
    | '/api/public/apify/runs'
    | '/api/public/brand/analyze'
    | '/api/public/instagram/analyze'
    | '/api/public/leads/start'
    | '/api/public/leads/status'
    | '/api/public/website/analyze'
  id:
    | '__root__'
    | '/'
    | '/leads'
    | '/runs'
    | '/search'
    | '/settings'
    | '/history/$id'
    | '/history/'
    | '/api/public/apify/import'
    | '/api/public/apify/runs'
    | '/api/public/brand/analyze'
    | '/api/public/instagram/analyze'
    | '/api/public/leads/start'
    | '/api/public/leads/status'
    | '/api/public/website/analyze'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LeadsRoute: typeof LeadsRoute
  RunsRoute: typeof RunsRoute
  SearchRoute: typeof SearchRoute
  SettingsRoute: typeof SettingsRoute
  HistoryIdRoute: typeof HistoryIdRoute
  HistoryIndexRoute: typeof HistoryIndexRoute
  ApiPublicApifyImportRoute: typeof ApiPublicApifyImportRoute
  ApiPublicApifyRunsRoute: typeof ApiPublicApifyRunsRoute
  ApiPublicBrandAnalyzeRoute: typeof ApiPublicBrandAnalyzeRoute
  ApiPublicInstagramAnalyzeRoute: typeof ApiPublicInstagramAnalyzeRoute
  ApiPublicLeadsStartRoute: typeof ApiPublicLeadsStartRoute
  ApiPublicLeadsStatusRoute: typeof ApiPublicLeadsStatusRoute
  ApiPublicWebsiteAnalyzeRoute: typeof ApiPublicWebsiteAnalyzeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/runs': {
      id: '/runs'
      path: '/runs'
      fullPath: '/runs'
      preLoaderRoute: typeof RunsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leads': {
      id: '/leads'
      path: '/leads'
      fullPath: '/leads'
      preLoaderRoute: typeof LeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history/': {
      id: '/history/'
      path: '/history'
      fullPath: '/history/'
      preLoaderRoute: typeof HistoryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history/$id': {
      id: '/history/$id'
      path: '/history/$id'
      fullPath: '/history/$id'
      preLoaderRoute: typeof HistoryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/website/analyze': {
      id: '/api/public/website/analyze'
      path: '/api/public/website/analyze'
      fullPath: '/api/public/website/analyze'
      preLoaderRoute: typeof ApiPublicWebsiteAnalyzeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/leads/status': {
      id: '/api/public/leads/status'
      path: '/api/public/leads/status'
      fullPath: '/api/public/leads/status'
      preLoaderRoute: typeof ApiPublicLeadsStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/leads/start': {
      id: '/api/public/leads/start'
      path: '/api/public/leads/start'
      fullPath: '/api/public/leads/start'
      preLoaderRoute: typeof ApiPublicLeadsStartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/instagram/analyze': {
      id: '/api/public/instagram/analyze'
      path: '/api/public/instagram/analyze'
      fullPath: '/api/public/instagram/analyze'
      preLoaderRoute: typeof ApiPublicInstagramAnalyzeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/brand/analyze': {
      id: '/api/public/brand/analyze'
      path: '/api/public/brand/analyze'
      fullPath: '/api/public/brand/analyze'
      preLoaderRoute: typeof ApiPublicBrandAnalyzeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/apify/runs': {
      id: '/api/public/apify/runs'
      path: '/api/public/apify/runs'
      fullPath: '/api/public/apify/runs'
      preLoaderRoute: typeof ApiPublicApifyRunsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/apify/import': {
      id: '/api/public/apify/import'
      path: '/api/public/apify/import'
      fullPath: '/api/public/apify/import'
      preLoaderRoute: typeof ApiPublicApifyImportRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LeadsRoute: LeadsRoute,
  RunsRoute: RunsRoute,
  SearchRoute: SearchRoute,
  SettingsRoute: SettingsRoute,
  HistoryIdRoute: HistoryIdRoute,
  HistoryIndexRoute: HistoryIndexRoute,
  ApiPublicApifyImportRoute: ApiPublicApifyImportRoute,
  ApiPublicApifyRunsRoute: ApiPublicApifyRunsRoute,
  ApiPublicBrandAnalyzeRoute: ApiPublicBrandAnalyzeRoute,
  ApiPublicInstagramAnalyzeRoute: ApiPublicInstagramAnalyzeRoute,
  ApiPublicLeadsStartRoute: ApiPublicLeadsStartRoute,
  ApiPublicLeadsStatusRoute: ApiPublicLeadsStatusRoute,
  ApiPublicWebsiteAnalyzeRoute: ApiPublicWebsiteAnalyzeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
